let D,cart=[],currentTab="site",$=x=>document.getElementById(x);
const e=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const wa=s=>{let n=String(s??"").replace(/\D/g,"");if(n.startsWith("00"))n=n.slice(2);if(n.startsWith("0"))n="20"+n.slice(1);return n};
async function load(){try{D=await (await fetch("/api/data?x="+Date.now(),{cache:"no-store"})).json()}catch{D={site:{name:"Sweet Home",title:"حلويات تُصنع<br><em>بحب</em> كل يوم.",description:""},products:[],branches:[],payments:["الدفع عند الاستلام","InstaPay","Vodafone Cash","Visa"],delivery:"التوصيل داخل مدينة المنصورة فقط"}}render()}
function render(){
brandName.textContent=D.site?.name||"Sweet Home";document.title=D.site?.name||"Sweet Home";
heroTitle.innerHTML=D.site?.title||"";heroDesc.textContent=D.site?.description||"";
let cs=["الكل",...new Set((D.products||[]).map(p=>p.cat).filter(Boolean))];
filters.innerHTML=cs.map((c,i)=>`<button class="filter ${i?"":"active"}" onclick="products('${e(c)}',this)">${e(c)}</button>`).join("");
products("الكل",document.querySelector(".filter"));
branchesGrid.innerHTML=(D.branches||[]).map(b=>`<div class="branch"><h3>${e(b.name)}</h3><p>📍 ${e(b.address)}</p><p>🕐 ${e(b.open||"10:00 ص")} - ${e(b.close||"1:00 ص")}</p><a href="tel:${e(b.phone)}">📞 ${e(b.phone)}</a><a target="_blank" rel="noopener" href="https://wa.me/${wa(b.wa||b.phone)}">واتساب الفرع</a></div>`).join("");
branchSelect.innerHTML='<option value="">اختار الفرع</option>'+(D.branches||[]).map((b,i)=>`<option value="${i}">${e(b.name)}</option>`).join("");
paymentSelect.innerHTML=(D.payments||[]).map(p=>`<option>${e(p)}</option>`).join("");
if(typeof adminOpen!=="undefined"&&new URLSearchParams(location.search).get("admin")==="1")openAdmin();
}
function products(c,b){document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b?.classList.add("active");let a=c==="الكل"?D.products:D.products.filter(p=>p.cat===c);productsGrid.innerHTML=a.map(p=>`<article class="product"><div class="pic">${p.image?`<img src="${e(p.image)}" alt="${e(p.name)}">`:p.emoji||"🍰"}</div><div class="body"><small>${e(p.cat)}</small><h3>${e(p.name)}</h3><div class="price">${Number(p.price||0)} جنيه</div><button class="add" onclick="add(${p.id})">+ أضف للسلة</button></div></article>`).join("")||'<p>لا توجد منتجات في هذا القسم حاليًا.</p>'}
function add(id){let x=cart.find(x=>x.id===id);x?x.q++:cart.push({id,q:1});cartRender();location.hash="order"}
function del(id){cart=cart.filter(x=>x.id!==id);cartRender()}
function cartRender(){if(!cart.length){cartItems.textContent="السلة فارغة";cartTotal.textContent="الإجمالي: 0 جنيه";return}let t=0;cartItems.innerHTML=cart.map(x=>{let p=D.products.find(p=>p.id===x.id);if(!p)return"";let v=Number(p.price||0)*x.q;t+=v;return`<div class="cartrow"><span>${e(p.name)} × ${x.q}</span><span>${v} ج <button onclick="del(${x.id})">حذف</button></span></div>`}).join("");cartTotal.textContent=`الإجمالي: ${t} جنيه`}
orderForm.onsubmit=x=>{x.preventDefault();if(!cart.length)return alert("أضف منتجًا أولاً");let b=D.branches[+branchSelect.value];if(!b)return alert("اختر الفرع أولاً");let number=wa(b.wa||b.phone);if(!number||number.length<11)return alert("رقم واتساب الفرع غير صحيح");let t=0,lines=cart.map(x=>{let p=D.products.find(p=>p.id===x.id),v=Number(p.price||0)*x.q;t+=v;return`• ${p.name} × ${x.q} = ${v} جنيه`}).join("\n");let m=`طلب Sweet Home\nالاسم: ${customerName.value}\nالموبايل: ${customerPhone.value}\nالعنوان: ${customerAddress.value}\nالفرع: ${b.name}\nالدفع: ${paymentSelect.value}\n\n${lines}\n\nالإجمالي: ${t} جنيه\n${D.delivery}`;location.href=`https://wa.me/${number}?text=${encodeURIComponent(m)}`}
function openAdmin(){adminModal.classList.remove("hidden");sessionStorage.getItem("sweetHomeAdmin")==="1"?showAdmin():(loginView.classList.remove("hidden"),adminView.classList.add("hidden"))}
function closeAdmin(){adminModal.classList.add("hidden")}
async function adminLogin(){let p=adminPassword.value.trim(),r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:p})});if(r.ok){sessionStorage.setItem("sweetHomeAdmin","1");showAdmin()}else loginMsg.textContent="كلمة المرور غير صحيحة."}
function showAdmin(){loginView.classList.add("hidden");adminView.classList.remove("hidden");tab(currentTab)}
function adminLogout(){sessionStorage.removeItem("sweetHomeAdmin");closeAdmin()}
function tab(t){currentTab=t;
if(t==="site")adminContent.innerHTML=`<div class="admin"><label>اسم الموقع</label><input id="n" value="${e(D.site.name)}"><label>العنوان</label><textarea id="ti">${e(D.site.title)}</textarea><label>الوصف</label><textarea id="de">${e(D.site.description)}</textarea><label>رابط اللوجو</label><input id="lo" value="${e(D.site.logo)}"><label>رابط البانر</label><input id="he" value="${e(D.site.hero)}"></div>`;
if(t==="products")adminContent.innerHTML=(D.products||[]).map((p,i)=>`<div class="admin"><div class="row"><div><label>الاسم</label><input data-p="${i}" data-k="name" value="${e(p.name)}"></div><div><label>السعر</label><input type="number" data-p="${i}" data-k="price" value="${p.price}"></div></div><div class="row"><div><label>القسم</label><input data-p="${i}" data-k="cat" value="${e(p.cat)}"></div><div><label>رابط الصورة</label><input data-p="${i}" data-k="image" value="${e(p.image)}"></div></div></div>`).join("")+`<button onclick="newProduct()">+ إضافة صنف جديد</button>`;
if(t==="branches")adminContent.innerHTML=(D.branches||[]).map((b,i)=>`<div class="admin"><div class="row"><div><label>اسم الفرع</label><input data-b="${i}" data-k="name" value="${e(b.name)}"></div><div><label>العنوان</label><input data-b="${i}" data-k="address" value="${e(b.address)}"></div></div><div class="row"><div><label>الهاتف</label><input data-b="${i}" data-k="phone" value="${e(b.phone)}"></div><div><label>واتساب</label><input data-b="${i}" data-k="wa" value="${e(b.wa)}"></div></div><div class="row"><div><label>فتح</label><input data-b="${i}" data-k="open" value="${e(b.open||"10:00 ص")}"></div><div><label>غلق</label><input data-b="${i}" data-k="close" value="${e(b.close||"1:00 ص")}"></div></div></div>`).join("")+`<button onclick="newBranch()">+ إضافة فرع</button>`;
}
function collect(){if(currentTab==="site"){D.site.name=n.value;D.site.title=ti.value;D.site.description=de.value;D.site.logo=lo.value;D.site.hero=he.value}document.querySelectorAll("[data-p]").forEach(x=>D.products[+x.dataset.p][x.dataset.k]=x.dataset.k==="price"?Number(x.value):x.value);document.querySelectorAll("[data-b]").forEach(x=>D.branches[+x.dataset.b][x.dataset.k]=x.value)}
async function saveAdmin(){collect();let p=prompt("كلمة مرور الإدارة للتأكيد","1234");if(p===null)return;let r=await fetch("/api/data",{method:"PUT",headers:{"Content-Type":"application/json","X-Admin-Password":p},body:JSON.stringify(D)});saveMsg.textContent=r.ok?"تم الحفظ بنجاح ✅":"فشل الحفظ.";if(r.ok)render()}
function newProduct(){D.products.push({id:Date.now(),name:"صنف جديد",cat:"حلويات شرقية",price:0,image:"",emoji:"🍰"});tab("products")}
function newBranch(){D.branches.push({name:"فرع جديد",address:"",phone:"",wa:"",open:"10:00 ص",close:"1:00 ص"});tab("branches")}
if(typeof adminOpen!=="undefined")adminOpen.onclick=openAdmin;
load();
